// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/inventory.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InventoryService_CreateSneakers_FullMethodName = "/inventoryservice.InventoryService/CreateSneakers"
	InventoryService_GetSneakers_FullMethodName    = "/inventoryservice.InventoryService/GetSneakers"
	InventoryService_UpdateSneakers_FullMethodName = "/inventoryservice.InventoryService/UpdateSneakers"
	InventoryService_DeleteSneakers_FullMethodName = "/inventoryservice.InventoryService/DeleteSneakers"
)

// InventoryServiceClient is the client API for InventoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InventoryServiceClient interface {
	CreateSneakers(ctx context.Context, in *CreateSneakersRequest, opts ...grpc.CallOption) (*Response, error)
	GetSneakers(ctx context.Context, in *GetSneakersRequest, opts ...grpc.CallOption) (*GetSneakersResponse, error)
	UpdateSneakers(ctx context.Context, in *UpdateSneakersRequest, opts ...grpc.CallOption) (*Response, error)
	DeleteSneakers(ctx context.Context, in *DeleteSneakersRequest, opts ...grpc.CallOption) (*Response, error)
}

type inventoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInventoryServiceClient(cc grpc.ClientConnInterface) InventoryServiceClient {
	return &inventoryServiceClient{cc}
}

func (c *inventoryServiceClient) CreateSneakers(ctx context.Context, in *CreateSneakersRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, InventoryService_CreateSneakers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) GetSneakers(ctx context.Context, in *GetSneakersRequest, opts ...grpc.CallOption) (*GetSneakersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSneakersResponse)
	err := c.cc.Invoke(ctx, InventoryService_GetSneakers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) UpdateSneakers(ctx context.Context, in *UpdateSneakersRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, InventoryService_UpdateSneakers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) DeleteSneakers(ctx context.Context, in *DeleteSneakersRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, InventoryService_DeleteSneakers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventoryServiceServer is the server API for InventoryService service.
// All implementations must embed UnimplementedInventoryServiceServer
// for forward compatibility.
type InventoryServiceServer interface {
	CreateSneakers(context.Context, *CreateSneakersRequest) (*Response, error)
	GetSneakers(context.Context, *GetSneakersRequest) (*GetSneakersResponse, error)
	UpdateSneakers(context.Context, *UpdateSneakersRequest) (*Response, error)
	DeleteSneakers(context.Context, *DeleteSneakersRequest) (*Response, error)
	mustEmbedUnimplementedInventoryServiceServer()
}

// UnimplementedInventoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInventoryServiceServer struct{}

func (UnimplementedInventoryServiceServer) CreateSneakers(context.Context, *CreateSneakersRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSneakers not implemented")
}
func (UnimplementedInventoryServiceServer) GetSneakers(context.Context, *GetSneakersRequest) (*GetSneakersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSneakers not implemented")
}
func (UnimplementedInventoryServiceServer) UpdateSneakers(context.Context, *UpdateSneakersRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSneakers not implemented")
}
func (UnimplementedInventoryServiceServer) DeleteSneakers(context.Context, *DeleteSneakersRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSneakers not implemented")
}
func (UnimplementedInventoryServiceServer) mustEmbedUnimplementedInventoryServiceServer() {}
func (UnimplementedInventoryServiceServer) testEmbeddedByValue()                          {}

// UnsafeInventoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InventoryServiceServer will
// result in compilation errors.
type UnsafeInventoryServiceServer interface {
	mustEmbedUnimplementedInventoryServiceServer()
}

func RegisterInventoryServiceServer(s grpc.ServiceRegistrar, srv InventoryServiceServer) {
	// If the following call pancis, it indicates UnimplementedInventoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InventoryService_ServiceDesc, srv)
}

func _InventoryService_CreateSneakers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSneakersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).CreateSneakers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_CreateSneakers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).CreateSneakers(ctx, req.(*CreateSneakersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_GetSneakers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSneakersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).GetSneakers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_GetSneakers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).GetSneakers(ctx, req.(*GetSneakersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_UpdateSneakers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSneakersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).UpdateSneakers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_UpdateSneakers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).UpdateSneakers(ctx, req.(*UpdateSneakersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_DeleteSneakers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSneakersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).DeleteSneakers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_DeleteSneakers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).DeleteSneakers(ctx, req.(*DeleteSneakersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InventoryService_ServiceDesc is the grpc.ServiceDesc for InventoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InventoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inventoryservice.InventoryService",
	HandlerType: (*InventoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSneakers",
			Handler:    _InventoryService_CreateSneakers_Handler,
		},
		{
			MethodName: "GetSneakers",
			Handler:    _InventoryService_GetSneakers_Handler,
		},
		{
			MethodName: "UpdateSneakers",
			Handler:    _InventoryService_UpdateSneakers_Handler,
		},
		{
			MethodName: "DeleteSneakers",
			Handler:    _InventoryService_DeleteSneakers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/inventory.proto",
}
